title: Shubham Vedi
# logo: /assets/img/profile.jpg
description: 🚀 Data Science Enthusiast | Generative AI | LLM | ChatGPT | Data Analyst | Machine Learning | NLP | SQL | Python | Excel | Power BI
show_downloads: true
theme: jekyll-theme-minimal
